<a href="https://colab.research.google.com/github/Priyadharshni18/ML-Practice/blob/Branch-1/Decision_tree_loan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
from google.colab import files
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [27]:
uploaded=files.upload()

Saving ML3.xlsx to ML3 (1).xlsx


In [45]:
df1=pd.read_excel('ML3 (1).xlsx')

In [46]:
dataset=pd.DataFrame(df1)

In [47]:
dataset.head()

loan_amnt  funded_amnt  ...  last_pymnt_amnt  loan_status
0     2500.0       2500.0  ...           119.66            0
1    10000.0      10000.0  ...           357.48            2
2     3000.0       3000.0  ...            67.79            1
3     5000.0       5000.0  ...           161.03            2
4     7000.0       7000.0  ...          1313.76            2

[5 rows x 20 columns]

In [48]:
# Importing the dataset
X=dataset.iloc[:,:-1].values
y=dataset.iloc[:, -1].values

In [49]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37138 entries, 0 to 37137
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   loan_amnt            37138 non-null  float64
 1   funded_amnt          37138 non-null  float64
 2   funded_amnt_inv      37138 non-null  float64
 3   Term(months)         37138 non-null  int64  
 4   int_rate             37138 non-null  float64
 5   installment          37138 non-null  float64
 6   grade                37138 non-null  int64  
 7   emp_length           37138 non-null  int64  
 8   home_ownership       37138 non-null  int64  
 9   annual_inc           37138 non-null  float64
 10  verification_status  37138 non-null  int64  
 11  purpose              37138 non-null  int64  
 12  dti                  37138 non-null  float64
 13  open_acc             37138 non-null  float64
 14  total_acc            37138 non-null  float64
 15  total_pymnt          37138 non-null 

In [51]:
dataset.drop(labels=['funded_amnt','funded_amnt_inv'],axis=1,inplace=True)

In [52]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
print(X_train)
print(y_train)
print(X_test)
print(y_test)


[[ 8400.    8400.    8400.   ...  6259.35  3880.92   208.27]
 [10000.   10000.    9950.   ...  2882.9   1581.16   200.83]
 [ 5000.    5000.    5000.   ...  5000.     768.34  2318.81]
 ...
 [20000.   20000.   18750.   ... 20000.    1231.15  1454.68]
 [10000.   10000.    9975.   ... 10000.     175.97  2677.7 ]
 [27000.   27000.   26975.   ...  3822.1   5454.44   713.99]]
[0 0 2 ... 2 2 0]
[[ 2500.        2500.        2500.       ...  2500.         349.47
   1148.63    ]
 [12000.       12000.       11975.       ...  2485.89      3119.37
     36.97    ]
 [ 7000.        7000.        7000.       ...  7000.         857.29
    256.42    ]
 ...
 [ 3500.        3500.        3364.367292 ...  3500.         735.99
    120.28    ]
 [ 1500.        1500.        1500.       ...  1500.         222.37
    564.03    ]
 [ 4800.        4800.        4800.       ...  4800.         440.48
    168.63    ]]
[2 0 2 ... 2 2 2]


In [53]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train[:,1:-1])
X_test = sc.transform(X_test[:,1:-1])
print(X_train)
print(X_test)
## neglate first column and run the test standard scaling procedure.

[[-0.33047824 -0.24451186  1.6419478  ... -0.19079646 -0.50860042
   1.63206197]
 [-0.07108626  0.00838923 -0.60903276 ... -0.8239928  -1.06137424
  -0.08188465]
 [-0.88168618 -0.79926264 -0.60903276 ... -0.72424781 -0.71477427
  -0.68765659]
 ...
 [ 1.55011358  1.44421479 -0.60903276 ...  0.98766472  1.74094325
  -0.34273728]
 [-0.07108626  0.01246828  1.6419478  ... -0.23627237  0.10379823
  -1.12913334]
 [ 2.68495346  2.78622219  1.6419478  ... -0.18842612 -0.90761358
   2.80476229]]
[[-1.28698614 -1.20716763 -0.60903276 ... -1.0474007  -1.12406053
  -0.99982866]
 [ 0.25315371  0.33879227  1.6419478  ... -0.48879452 -1.12637054
   1.06450012]
 [-0.55744621 -0.47293865 -0.60903276 ... -0.49297716 -0.38734527
  -0.62136465]
 ...
 [-1.12486616 -1.06613573 -0.60903276 ... -0.89389745 -0.96034603
  -0.71176614]
 [-1.44910612 -1.37032962 -0.60903276 ... -1.17218461 -1.28777503
  -1.09455272]
 [-0.91411018 -0.83189504 -0.60903276 ... -0.78268838 -0.74751717
  -0.93200146]]


In [54]:
# Training the Decision Tree Classification model on the Training set
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)


DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [55]:
# Predicting a new result
print(classifier.predict(sc.transform([[2500,60,15.27,59.83,2,1,4,30000,1,0,1,3,4,1008.71,456.46,435.17,119.66]])))



[1]


In [56]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[2 2]
 [0 0]
 [2 2]
 ...
 [2 2]
 [2 2]
 [2 2]]


In [57]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)


[[1248   22   20]
 [  17  215   43]
 [  21   31 7668]]


0.9834141087775983