<a href="https://colab.research.google.com/github/Priyadharshni18/ML-Practice/blob/Branch-1/KNN_ALGO_LOAN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from google.colab import files


In [4]:
uploaded=files.upload()

Saving ML3.xlsx to ML3.xlsx


In [5]:
df1=pd.read_excel('ML3.xlsx')

In [38]:
df2=pd.DataFrame(df1)

In [40]:
df2.head()

loan_amnt  funded_amnt  ...  last_pymnt_amnt  loan_status
0     2500.0       2500.0  ...           119.66            0
1    10000.0      10000.0  ...           357.48            2
2     3000.0       3000.0  ...            67.79            1
3     5000.0       5000.0  ...           161.03            2
4     7000.0       7000.0  ...          1313.76            2

[5 rows x 20 columns]

In [41]:
df2.drop(labels=['funded_amnt','funded_amnt_inv'],axis=1,inplace=True)

In [42]:
df2.head()

loan_amnt  Term(months)  ...  last_pymnt_amnt  loan_status
0     2500.0            60  ...           119.66            0
1    10000.0            36  ...           357.48            2
2     3000.0            60  ...            67.79            1
3     5000.0            36  ...           161.03            2
4     7000.0            60  ...          1313.76            2

[5 rows x 18 columns]

In [44]:
# Importing the dataset
X = df2.iloc[:, :-1].values
y = df2.iloc[:, -1].values

In [45]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
print(X_train)
print(y_train)
print(X_test)
print(y_test)


[[8.40000e+03 6.00000e+01 1.68900e+01 ... 6.25935e+03 3.88092e+03
  2.08270e+02]
 [1.00000e+04 3.60000e+01 1.59500e+01 ... 2.88290e+03 1.58116e+03
  2.00830e+02]
 [5.00000e+03 3.60000e+01 1.13600e+01 ... 5.00000e+03 7.68340e+02
  2.31881e+03]
 ...
 [2.00000e+04 3.60000e+01 1.13600e+01 ... 2.00000e+04 1.23115e+03
  1.45468e+03]
 [1.00000e+04 6.00000e+01 1.66900e+01 ... 1.00000e+04 1.75970e+02
  2.67770e+03]
 [2.70000e+04 6.00000e+01 1.99100e+01 ... 3.82210e+03 5.45444e+03
  7.13990e+02]]
[0 0 2 ... 2 2 0]
[[2.50000e+03 3.60000e+01 1.03700e+01 ... 2.50000e+03 3.49470e+02
  1.14863e+03]
 [1.20000e+04 6.00000e+01 1.90300e+01 ... 2.48589e+03 3.11937e+03
  3.69700e+01]
 [7.00000e+03 3.60000e+01 7.66000e+00 ... 7.00000e+03 8.57290e+02
  2.56420e+02]
 ...
 [3.50000e+03 3.60000e+01 1.28400e+01 ... 3.50000e+03 7.35990e+02
  1.20280e+02]
 [1.50000e+03 3.60000e+01 1.02500e+01 ... 1.50000e+03 2.22370e+02
  5.64030e+02]
 [4.80000e+03 3.60000e+01 5.79000e+00 ... 4.80000e+03 4.40480e+02
  1.68630e+02]

In [46]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train)
print(X_test)


[[-2.85842597e-01  1.64194780e+00  1.30092217e+00 ... -5.08600416e-01
   1.63206197e+00 -6.71417215e-01]
 [-4.23042302e-02 -6.09032761e-01  1.04736383e+00 ... -1.06137424e+00
  -8.18846487e-02 -6.75415664e-01]
 [-8.03361626e-01 -6.09032761e-01 -1.90756173e-01 ... -7.14774273e-01
  -6.87656595e-01  4.62841815e-01]
 ...
 [ 1.47981056e+00 -6.09032761e-01 -1.90756173e-01 ...  1.74094325e+00
  -3.42737284e-01 -1.56409792e-03]
 [-4.23042302e-02  1.64194780e+00  1.24697359e+00 ...  1.03798233e-01
  -1.12913334e+00  6.55718625e-01]
 [ 2.54529092e+00  1.64194780e+00  2.11554579e+00 ... -9.07613584e-01
   2.80476229e+00 -3.99630148e-01]]
[[-1.18389032 -0.60903276 -0.45780166 ... -1.12406053 -0.99982866
  -0.16604332]
 [ 0.26211873  1.6419478   1.87817202 ... -1.12637054  1.06450012
  -0.76347829]
 [-0.49893867 -0.60903276 -1.18880498 ... -0.38734527 -0.62136465
  -0.64554015]
 ...
 [-1.03167884 -0.60903276  0.20846335 ... -0.96034603 -0.71176614
  -0.71870533]
 [-1.3361018  -0.60903276 -0.490170

In [47]:
# Training the K-NN model on the Training set
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [48]:
# Predicting a new result
print(classifier.predict(sc.transform([[2500,60,15.27,59.83,2,1,4,30000,1,0,1,3,4,1008.71,456.46,435.17,119.66]])))


[0]


In [50]:
X_train[0:1]

array([[-0.2858426 ,  1.6419478 ,  1.30092217, -0.56331486,  1.01650274,
        -0.85922274,  0.96097964, -0.36729442,  0.11814364,  2.7282528 ,
        -0.00559939,  0.21375815, -0.63520774, -0.19079646, -0.50860042,
         1.63206197, -0.67141721]])

In [51]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))


[[2 2]
 [0 0]
 [2 2]
 ...
 [2 2]
 [2 2]
 [2 2]]


In [52]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)



[[ 692   32  566]
 [  23   91  161]
 [  98  100 7522]]


0.8944534194938072